#!/bin/sh

host="`hostname`"
hostbase="`basename $host .complang.tuwien.ac.at`"
dmp="`basename $1 .fs`.$hostbase.dmp"

xnorun $1 >$dmp 2>&1
echo >>$dmp 2>&1

xrun $1 >>$dmp 2>&1
echo >>$dmp 2>&1

xgnorun $1 >>$dmp 2>&1
echo >>$dmp 2>&1

xgrun $1 >>$dmp 2>&1
echo >>$dmp 2>&1
